/**
 * Created by Administrator on 2018\12\3 0003.
 */
const field1 = [
    { question: '和80相邻的两个数是？', answers: [ { text: '81和82', type: 'no'}, { text: '79和81', type: 'yes'} ], },
    { question: '和56相邻的两个数是？', answers: [ { text: '54和55', type: 'no'}, { text: '55和57', type: 'yes'} ], },
    { question: '和24相邻的两个数是？', answers: [ { text: '23和25', type: 'yes'}, { text: '25和26', type: 'no'} ], },
    { question: '76到82中间有几个数？', answers: [ { text: '5', type: 'yes'}, { text: '6', type: 'no'} ], },
    { question: '23到28中间有几个数？', answers: [ { text: '5', type: 'yes'}, { text: '6', type: 'no'} ], },
    { question: '65到69中间有几个数？', answers: [ { text: '3', type: 'yes'}, { text: '4', type: 'no'} ], },
    { question: '83后面的第五个数是？', answers: [ { text: '87', type: 'no'}, { text: '88', type: 'yes'} ], },
    { question: '51前面的第四个数是？', answers: [ { text: '47', type: 'yes'}, { text: '46', type: 'no'} ], },
    { question: '37后面的第五个数是？', answers: [ { text: '42', type: 'yes'}, { text: '41', type: 'no'} ], },
    { question: '88读作？', answers: [ { text: '八十加八', type: 'no'}, { text: '八十八', type: 'yes'} ], },
    { question: '55读作？', answers: [ { text: '五十加五', type: 'no'}, { text: '五十五', type: 'yes'} ], },
    { question: '11读作？', answers: [ { text: '十加一', type: 'no'}, { text: '一十一', type: 'yes'} ], },
    { question: '47到53中间有几个数？', answers: [ { text: '5', type: 'yes'}, { text: '6', type: 'no'} ], },
    { question: '45是由（）组成的？', answers: [ { text: '4个5', type: 'no'}, { text: '4个十和5个一', type: 'yes'} ], },
    { question: '11是由（）组成的？', answers: [ { text: '1和1', type: 'no'}, { text: '1个十和1个一', type: 'yes'} ], },
    { question: '55是由（）组成的？', answers: [ { text: '5和5', type: 'no'}, { text: '5个十和5个一', type: 'yes'} ], },
    { question: '3+7（）4+5？', answers: [ { text: '<', type: 'no'}, { text: '>', type: 'yes'} ], },
    { question: '2+3-4（）0？', answers: [ { text: '<', type: 'no'}, { text: '>', type: 'yes'} ], },
    { question: '2+5-6（）3？', answers: [ { text: '<', type: 'yes'}, { text: '>', type: 'no'} ], },
    { question: '35里有几个十？', answers: [ { text: '5', type: 'no'}, { text: '3', type: 'yes'} ], },
    { question: '12里有几个2？', answers: [ { text: '1', type: 'no'}, { text: '6', type: 'yes'} ], },
    { question: '13这个数，个位上的数是？', answers: [ { text: '1', type: 'no'}, { text: '3', type: 'yes'} ], },
    { question: '54这个数，十位上的数是？', answers: [ { text: '1', type: 'no'}, { text: '3', type: 'yes'} ], },
    { question: '32这个数，十位上的数是？', answers: [ { text: '2', type: 'no'}, { text: '3', type: 'yes'} ], },
    { question: '1个十和6个一，组成的数是？', answers: [ { text: '61', type: 'no'}, { text: '16', type: 'yes'} ], },
    { question: '5个一和1个十，组成的数是？', answers: [ { text: '51', type: 'no'}, { text: '15', type: 'yes'} ], },
    { question: '34这个数，十位上的数是？', answers: [ { text: '4', type: 'no'}, { text: '3', type: 'yes'} ], },
];
const field2 = [
    { question: '36 + 20 ？', answers: [ { text: '38', type: 'no'}, { text: '56', type: 'yes'}, { text: '66', type: 'no' } ], },
    { question: '45 + 55 ？', answers: [ { text: '90', type: 'no'}, { text: '100', type: 'yes'}, { text: '110', type: 'no' } ], },
    { question: '23 + 8 ？', answers: [ { text: '31', type: 'yes'}, { text: '21', type: 'no'}, { text: '41', type: 'no' } ], },
    { question: '18 + 27 ？', answers: [ { text: '55', type: 'no'}, { text: '35', type: 'no'}, { text: '45', type: 'yes' } ], },
    { question: '100 - 50 ？', answers: [ { text: '40', type: 'no'}, { text: '50', type: 'yes'}, { text: '60', type: 'no' } ], },
    { question: '41 - 9 ？', answers: [ { text: '32', type: 'yes'}, { text: '30', type: 'no'}, { text: '31', type: 'no' } ], },
    { question: '75 - 27 ？', answers: [ { text: '48', type: 'yes'}, { text: '58', type: 'no'}, { text: '57', type: 'no' } ], },
    { question: '82 - 6 ？', answers: [ { text: '76', type: 'yes'}, { text: '74', type: 'no'}, { text: '78', type: 'no' } ], },
    { question: '2 × 5 ？', answers: [ { text: '5', type: 'no'}, { text: '10', type: 'yes'}, { text: '15', type: 'no' } ], },
    { question: '3 × 6 ？', answers: [ { text: '12', type: 'no'}, { text: '18', type: 'yes'}, { text: '15', type: 'no' } ], },
    { question: '4 × 5 ？', answers: [ { text: '16', type: 'no'}, { text: '20', type: 'yes'}, { text: '25', type: 'no' } ], },
    { question: '3 × 9 ？', answers: [ { text: '18', type: 'no'}, { text: '27', type: 'yes'}, { text: '24', type: 'no' } ], },
    { question: '15 ➗ 5 ？', answers: [ { text: '2', type: 'no'}, { text: '3', type: 'yes'}, { text: '4', type: 'no' } ], },
    { question: '21 ➗ 7 ？', answers: [ { text: '2', type: 'no'}, { text: '3', type: 'yes'}, { text: '4', type: 'no' } ], },
    { question: '54 ➗ 9 ？', answers: [ { text: '5', type: 'no'}, { text: '6', type: 'yes'}, { text: '7', type: 'no' } ], },
    { question: '48 ➗ 6 ？', answers: [ { text: '7', type: 'no'}, { text: '8', type: 'yes'}, { text: '9', type: 'no' } ], },
    { question: '3 × 6 （） 28 ？', answers: [ { text: '>', type: 'no'}, { text: '=', type: 'no'}, { text: '<', type: 'yes' } ], },
    { question: '4 × 4 （） 18 ？', answers: [ { text: '>', type: 'no'}, { text: '=', type: 'no'}, { text: '<', type: 'yes' } ], },
    { question: '2 × 5 （） 12 ？', answers: [ { text: '>', type: 'no'}, { text: '=', type: 'no'}, { text: '<', type: 'yes' } ], },
    { question: '6 × 9 （） 55 ？', answers: [ { text: '>', type: 'no'}, { text: '=', type: 'no'}, { text: '<', type: 'yes' } ], },
];
const field3 = [
    { question: '小亮出去跑步，跑60米大概需要13（）？', answers: [ { text: '小时', type: 'no'}, { text: '分钟', type: 'no'}, { text: '秒', type: 'yes' } ], },
    { question: '小明写了100个数，用了3（）？', answers: [ { text: '小时', type: 'no'}, { text: '分钟', type: 'yes'}, { text: '秒', type: 'no' } ], },
    { question: '小明看完电视的时间是9：00，用了1小时10分钟，请问小明是什么时候开始看电视的？', answers: [ { text: '10：10', type: 'no'}, { text: '7：50', type: 'yes'}, { text: '7：10', type: 'no' } ], },
    { question: '一个苹果大约重300（）？', answers: [ { text: '克', type: 'yes'}, { text: '千克', type: 'no'}, { text: '吨', type: 'no' } ], },
    { question: '20张卡片的厚度大约是20（） ？', answers: [ { text: '毫米', type: 'yes'}, { text: '厘米', type: 'no'}, { text: '4分米', type: 'no' } ], },
    { question: '小红的身高是（）？', answers: [ { text: '毫米', type: 'no'}, { text: '厘米', type: 'yes'}, { text: '分米', type: 'no' } ], },
    { question: '1吨（）960千克？', answers: [ { text: '>', type: 'yes'}, { text: '=', type: 'no'}, { text: '<', type: 'no' } ], },
    { question: '4千克（）4000克？', answers: [ { text: '>', type: 'no'}, { text: '=', type: 'yes'}, { text: '<', type: 'no' } ], },
    { question: '5小时（）500分钟？', answers: [ { text: '>', type: 'no'}, { text: '=', type: 'no'}, { text: '<', type: 'yes' } ], },
    { question: '120秒（）2分钟？', answers: [ { text: '>', type: 'no'}, { text: '=', type: 'yes'}, { text: '<', type: 'no' } ], },
    { question: '时针走完一大格是（）？', answers: [ { text: '5小时', type: 'no'}, { text: '1小时', type: 'yes'}, { text: '60小时', type: 'no' } ], },
    { question: '一支铅笔长5厘米，用去了7毫米，还剩（）毫米？', answers: [ { text: '57', type: 'no'}, { text: '43', type: 'yes'}, { text: '23', type: 'no' } ], },
    { question: '1袋大米重25千克，（）袋大米重1吨？', answers: [ { text: '50', type: 'no'}, { text: '40', type: 'yes'}, { text: '60', type: 'no' } ], },
    { question: '一个数减去329，差是488.这个数是（）？', answers: [ { text: '717', type: 'no'}, { text: '817', type: 'yes'}, { text: '707', type: 'no' } ], },
    { question: '297和495的和接近（）？', answers: [ { text: '700', type: 'no'}, { text: '800', type: 'yes'}, { text: '900', type: 'no' } ], },
    { question: '钟表上走得最快的指针是（）？', answers: [ { text: '时针', type: 'no'}, { text: '分针', type: 'no'}, { text: '秒针', type: 'yes' } ], },
    { question: '9只青蛙有（）条腿？', answers: [ { text: '18', type: 'no'}, { text: '27', type: 'no'}, { text: '36', type: 'yes' } ], },
    { question: '1本书350页，第一天看了126页，第二天看了207页，这本书还剩页，正确的列式是（）？', answers: [ { text: '350-126+207', type: 'no'}, { text: '250+126-207', type: 'no'}, { text: '350-126-207', type: 'yes' } ], },
];
const field4 = [
    { question: '16 × 30 （）15 × 30 ？', answers: [ { text: '>', type: 'yes'}, { text: '=', type: 'no'}, { text: '<', type: 'no' } ], },
    { question: '75 × 48 （）75 × 86 ？', answers: [ { text: '>', type: 'no'}, { text: '=', type: 'no'}, { text: '<', type: 'yes' } ], },
    { question: '140 × 80（）80 × 160 ？', answers: [ { text: '>', type: 'no'}, { text: '=', type: 'no'}, { text: '<', type: 'yes' } ], },
    { question: '90 × 159（）90 × 160 ？', answers: [ { text: '>', type: 'no'}, { text: '=', type: 'no'}, { text: '<', type: 'yes' } ], },
    { question: '300 × 15（）345 × 17 ？', answers: [ { text: '>', type: 'no'}, { text: '=', type: 'no'}, { text: '<', type: 'yes' } ], },
    { question: '650万（）6050000 ？', answers: [ { text: '>', type: 'yes'}, { text: '=', type: 'no'}, { text: '<', type: 'no' } ], },
    { question: '12 × 90（）24 × 45 ？', answers: [ { text: '>', type: 'no'}, { text: '=', type: 'yes'}, { text: '<', type: 'no' } ], },
    { question: '过直线外一点，可以画（）条直线与已知直线平行？', answers: [ { text: '0', type: 'no'}, { text: '1', type: 'yes'}, { text: '无数', type: 'no' } ], },
    { question: '角的大小是由（）决定的？', answers: [ { text: '两条边的长短', type: 'no'}, { text: '两条边张开的程度', type: 'yes'}, { text: '顶点的位置', type: 'no' } ], },
    { question: '三位数乘以两位数，积是（）？', answers: [ { text: '四位数', type: 'no'}, { text: '五位数', type: 'yes'}, { text: '六位数', type: 'no' } ], },
    { question: '一条直线上可以截取（）条线段？', answers: [ { text: '1', type: 'no'}, { text: '2', type: 'no'}, { text: '无数', type: 'yes' } ], },
    { question: '角的两条边都是（）？', answers: [ { text: '直线', type: 'no'}, { text: '线段', type: 'no'}, { text: '射线', type: 'yes' } ], },
    { question: '60 + 40 × 3 ？', answers: [ { text: '300', type: 'no'}, { text: '160', type: 'no'}, { text: '180', type: 'yes' } ], },
    { question: '75 - 75 ➗ 5 ？', answers: [ { text: '0', type: 'no'}, { text: '50', type: 'no'}, { text: '60', type: 'yes' } ], },
    { question: '720 ➗ 8 × 9 ？', answers: [ { text: '10', type: 'no'}, { text: '81', type: 'no'}, { text: '810', type: 'yes' } ], },
];